export default {
  products: [
    {
      _id: '1',
      name: 'Produto 1',
      category: 'Categoria A',
      image: '/images/product-1.jpg',
      price: 59,
      brand: 'Marca Famosa',
      rating: 4.5,
      numReviews: 10,
      countInStock: 6,
    },
    {
      _id: '2',
      name: 'Produto 2',
      category: 'Categoria B',
      image: '/images/product-2.jpg',
      price: 70,
      brand: 'Marca Famosa',
      rating: 5,
      numReviews: 51,
    },
    {
      _id: '3',
      name: 'Produto 3',
      category: 'Categoria A',
      image: '/images/product-3.jpg',
      price: 59,
      brand: 'Marca Chique',
      rating: 4,
      numReviews: 45,
    },
    {
      _id: '4',
      name: 'Produto 4',
      category: 'Categoria A',
      image: '/images/product-4.jpg',
      price: 90,
      brand: 'Marca Famosa',
      rating: 2.5,
      numReviews: 198,
      countInStock: 6,
    },
    {
      _id: '5',
      name: 'Produto 5',
      category: 'Categoria B',
      image: '/images/product-5.jpg',
      price: 119,
      brand: 'Marca Legal',
      rating: 3.5,
      numReviews: 89,
      countInStock: 6,
    },
    {
      _id: '6',
      name: 'Produto 6',
      category: 'Categoria C',
      image: '/images/product-6.jpg',
      price: 85,
      brand: 'Marca Famosa',
      rating: 4.5,
      numReviews: 45,
      countInStock: 6,
    },
  ],
};